# This file was generated by GoReleaser. DO NOT EDIT.
cask "gorgias-pp-cli" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "33d189d115de5d32cfeeb05cf21c4e65aa72a552cd732ec0edb0e76f7e5d4249"
      url "https://github.com/chrisyoungcooks/gorgias-pp-cli/releases/download/v#{version}/gorgias-pp-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "248a0cb1eaa9f02a481c2dbdc9b1c86e53e8a76bbd1d9c3e4426014b40bbd108"
      url "https://github.com/chrisyoungcooks/gorgias-pp-cli/releases/download/v#{version}/gorgias-pp-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6313cafdc3d43ccf654d6adc9d29feceb549b589e8c8295b22a74cad774ab647"
      url "https://github.com/chrisyoungcooks/gorgias-pp-cli/releases/download/v#{version}/gorgias-pp-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f3c07ca61c057641b0dd0d32f63f06f6270694ee9cfaf2bd0fca91e701a6e853"
      url "https://github.com/chrisyoungcooks/gorgias-pp-cli/releases/download/v#{version}/gorgias-pp-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gorgias-pp-cli"
  desc "Every Gorgias support workflow, agent-native, in one binary."
  homepage "https://github.com/chrisyoungcooks/gorgias-pp-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gorgias-pp-cli"
  binary "gorgias-pp-mcp"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/gorgias-pp-cli"]
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/gorgias-pp-mcp"]
  end

  # No zap stanza required

end
