# This file was generated by GoReleaser. DO NOT EDIT.
cask "gorgias-pp-cli" do
  version "0.1.6"

  on_macos do
    on_intel do
      sha256 "caa4e5d3fcc366c839c6160aa82fa8e2ecd4b95e9066f58eb8105aa022ccd09c"
      url "https://github.com/chrisyoungcooks/gorgias-pp-cli/releases/download/v#{version}/gorgias-pp-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b0eba31692e9e83ead1bf23c71d5ef3c0bc88834ae250d3d64534da2187743ca"
      url "https://github.com/chrisyoungcooks/gorgias-pp-cli/releases/download/v#{version}/gorgias-pp-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "abdf4b491978e099abdd900c52562de791f0841c4aed9e1c3787638e1edbf1cb"
      url "https://github.com/chrisyoungcooks/gorgias-pp-cli/releases/download/v#{version}/gorgias-pp-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "87ee1e4ba99b8e5da62eddf64e9a6fc899a02c6247d6454a98f6f83c1ea34a1e"
      url "https://github.com/chrisyoungcooks/gorgias-pp-cli/releases/download/v#{version}/gorgias-pp-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gorgias-pp-cli"
  desc "Every Gorgias support workflow, agent-native, in one binary."
  homepage "https://github.com/chrisyoungcooks/gorgias-pp-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gorgias-pp-cli"
  binary "gorgias-pp-mcp"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/gorgias-pp-cli"]
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/gorgias-pp-mcp"]
  end

  # No zap stanza required

end
