# This file was generated by GoReleaser. DO NOT EDIT.
cask "gorgias-pp-cli" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "a8481998b3482a71b78df2e0e4f439475a713281dba1ba543741af43ab9d4efb"
      url "https://github.com/chrisyoungcooks/gorgias-pp-cli/releases/download/v#{version}/gorgias-pp-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "700b71ee94d756d2e4b060bb5af1bf16d225f1739db0cedcb2828f661337172b"
      url "https://github.com/chrisyoungcooks/gorgias-pp-cli/releases/download/v#{version}/gorgias-pp-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b7c80c28fb8222a94f3f08f0c4acc099fd6909bcd8db5626c7b7d1ae4565d12a"
      url "https://github.com/chrisyoungcooks/gorgias-pp-cli/releases/download/v#{version}/gorgias-pp-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6ddb0dde5ab1fb879e1efef621ee999664e5f37d4831cc820896fe8de9746cca"
      url "https://github.com/chrisyoungcooks/gorgias-pp-cli/releases/download/v#{version}/gorgias-pp-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gorgias-pp-cli"
  desc "Every Gorgias support workflow, agent-native, in one binary."
  homepage "https://github.com/chrisyoungcooks/gorgias-pp-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gorgias-pp-cli"

  # No zap stanza required

end
